# Site settings
title:       "演程序猿的员"
email:       yangyang@thoughtworks.com
author:      Yang Yang
description: "演有致极，技无穷尽"
baseurl:     ""
url:         "http://zacyang.github.io/"

# Google analytics
google_analytics: "UA-64709665-1"

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: httpzacyanggithubio

# Social icons
show_social_icons: true
github_username: 'zacyang'
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
  permalink:    /:month-:day-:year/:title.html
paginate:     3
sass:
  compressed: true
