#pluigins
gems: [jekyll-paginate]
plugins: [jekyll-paginate]

# Site settings
title:       "最强(壮)的程序员"
email:       
author:      Yang Yang
description: "演有致极，技无穷尽"
baseurl:     ""
url:         "https://www.yangyang.ninja/"

# Google analytics
google_analytics: "UA-64709665-1"

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: httpzacyanggithubio

# Social icons
show_social_icons: true
github_username: 'zacyang'
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'share this!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:    kramdown
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
  # permalink:    /:month-:day-:year/:title.html
paginate:     3
# paginate_path: "/page:num/"
sass:
  compressed: true

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false